version: "3"
services:
  main-app:
    image: arlet2/selectel-front
    ports:
      - "127.0.0.1:8080:8080"

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
